### ISSUE TITLE
加载出错

### ISSUE THREAD

**Issue by mackxu** [Bob1993/react-native-navigationbar#2]
ios 9.3

import NavigatorBar from 'react-native-navigationbar';
报出错误：
node_modules/react-native-navigationbar/lib/add@3x.png: Unexpected character '�' (1:0)

请问怎么解决？

**Comment by poberwong** [comment]
新版本已经把add@3x.png去掉了...... 这个原因是packager在动态加载资源文件的时候，针对图片的一个bug，一般重启packager就ok 了
