### ISSUE TITLE
关于在让action是一张图片的用法

### ISSUE THREAD

**Issue by cl1069573062** [Bob1993/react-native-navigationbar#4]
我在使用你的 react-native-navigationbar开源项目时，我想让最右边的actionName是一张图片，请问这样的需求，我可以怎么做到，你有这样的api吗？非常感谢

**Comment by poberwong** [comment]
哈哈，多谢理解..... api已经支持了，回调函数是renderAction
`renderAction={...}` 在回调函数中只需要返回你需要渲染的视图就可以了，可以是任意视图

**Comment by poberwong** [comment]
今天白天会写完完整的README.md并发布到npm上，多谢支持
